version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://root:root@postgres/test_db
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: email@email.com
      PGADMIN_DEFAULT_PASSWORD: heslo
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - postgres
    